# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_egfk', '0002_a_b_c_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('alpha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_egfk.Alpha')),
            ],
        ),
        migrations.RenameModel(
            old_name='D',
            new_name='TestSampleModel',
        ),
        migrations.RemoveField(
            model_name='main',
            name='text',
        ),
    ]
